#!/usr/bin/env python3
"""Generate a signature-agnostic export proxy for a system DLL.

Reads the export table of a Windows DLL and emits two files under
src/proxy/generated:

  <stem>_proxy.gen.cpp   tail-jump thunks, a resolver table, and a Bind entry
  <stem>.def             the export list, real names aliased to the thunks

The thunks forward by an indirect jump through a resolved pointer, so every
calling convention and signature is preserved without being declared. Rerun
this when a target DLL's export set changes; the output is otherwise stable.

Usage:
  python tools/gen_proxy.py version /mnt/c/Windows/System32/version.dll
"""

import sys
from pathlib import Path

import pefile

HERE = Path(__file__).resolve().parent
OUT_DIR = HERE.parent / "src" / "proxy" / "generated"


def collect_exports(dll_path: str):
    pe = pefile.PE(dll_path, fast_load=True)
    pe.parse_data_directories(
        directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]]
    )
    exports = []
    for sym in pe.DIRECTORY_ENTRY_EXPORT.symbols:
        if sym.name is None:
            continue
        exports.append((sym.ordinal, sym.name.decode()))
    exports.sort(key=lambda e: e[0])
    return exports


def emit(stem: str, real_dll: str, exports):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cpp = OUT_DIR / f"{stem}_proxy.gen.cpp"
    def_path = OUT_DIR / f"{stem}.def"

    slots = []
    stubs = []
    table = []
    dllname = f"L\"{real_dll}\""
    for ordinal, name in exports:
        slot = f"g_{stem}_{ordinal}"
        stub = f"odg_{stem}_stub_{ordinal}"
        slots.append(f"void* {slot} = nullptr;")
        stubs.append(
            f"__attribute__((naked)) void {stub}() {{ "
            f"__asm__ volatile(\"jmp *{slot}(%rip)\"); }}"
        )
        table.append(f'    {{"{name}", &{slot}}},')

    cpp.write_text(
        f"// GENERATED by tools/gen_proxy.py from {real_dll}. Do not edit.\n"
        f'#include "proxy/proxy.h"\n\n'
        f"#include <wchar.h>\n\n"
        f"#if defined(__clang__) || defined(__GNUC__)\n\n"
        f'extern "C" {{\n'
        + "\n".join(slots)
        + "\n\n"
        + "\n".join(stubs)
        + "\n}\n\n"
        f"namespace {{\n"
        f"const odg::proxy::Export k_{stem}_exports[] = {{\n"
        + "\n".join(table)
        + "\n};\n}\n\n"
        f"namespace odg::proxy {{\n"
        f"bool BindActive(const wchar_t* loaded_file_name) {{\n"
        f"    if (_wcsicmp(loaded_file_name, {dllname}) != 0)\n"
        f"        return false;\n"
        f"    return Bind({dllname}, k_{stem}_exports,\n"
        f"                sizeof(k_{stem}_exports) / sizeof(k_{stem}_exports[0]));\n"
        f"}}\n"
        f"}}\n\n"
        f"#endif\n",
        encoding="utf-8",
    )

    lines = ["EXPORTS"]
    for ordinal, name in exports:
        lines.append(f"    {name}=odg_{stem}_stub_{ordinal} @{ordinal}")
    def_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote {cpp.relative_to(OUT_DIR.parent.parent.parent)} "
          f"and {def_path.name} ({len(exports)} exports)")


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    stem, dll_path = sys.argv[1], sys.argv[2]
    emit(stem, Path(dll_path).name, collect_exports(dll_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
